---
name: main

on: push

jobs:
  docker-publish:
    name: Build and publish Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Determine version of latest upstream release
        id: upstream-latest-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          latest_version=$(gh release view \
           --repo ironsheep/RPi-Reporter-MQTT2HA-Daemon \
           --json tagName --jq '.|to_entries[]|.value')
          echo "value=$latest_version" >> "$GITHUB_OUTPUT"

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up QEMU for more platforms supported by Buildx
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare repository name for Github Container Registry
        id: ghcr-repo-name
        # GHCR repository name should be lower case
        run: |-
          ghcr_repo=$(echo "${{ github.event.repository.name }}" \
            | tr "[[:upper:]]" "[[:lower:]]")
          echo "value=$ghcr_repo" >> "$GITHUB_OUTPUT"

      - name: Build and push images
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |-
            version="${{ steps.upstream-latest-version.outputs.value }}"
          platforms: linux/arm/v7,linux/arm/v6,linux/arm64
          push: true
          tags:
            "ghcr.io/${{ github.repository_owner }}\
            /${{ steps.ghcr-repo-name.outputs.value }}:latest

            ghcr.io/${{ github.repository_owner }}\
            /${{ steps.ghcr-repo-name.outputs.value }}\
            :${{ steps.upstream-latest-version.outputs.value }}"
