---
name: main

on: push

jobs:
  docker-publish:
    name: Build and publish Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Determine version of latest upstream release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ironsheep
          REPO: RPi-Reporter-MQTT2HA-Daemon
        run: >-
          latest_version=$(gh release view
           --json tagName --jq '.|to_entries[]|.value')
          echo "LATEST_VERSION=$latest_version" >> $GITHUB_ENV

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up QEMU for more platforms supported by Buildx
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        uses: docker/build-push-action@v4
        with:
          context: .
          build_args:
            - version=$LATEST_VERSION
          platforms: linux/arm/v7,linux/arm/v6,linux/arm64,linux/amd64
          push: true
          tags:
            "ghcr.io/${{ github.repository_owner }}\
            /${{ github.event.repository.name }}:latest

            ghcr.io/${{ github.repository_owner }}\
            /${{ github.event.repository.name }}\
            :$LATEST_VERSION"
